AppBundle\Entity\Usuario:
    properties:
    # Your custom fields in your user entity, here is an example with FirstName
        nombre:
            - NotBlank:
                message: acme_user.nombre.blank
                groups: [ "Registration", "Profile" ]
            - Length:
                min: 2
                minMessage: acme_user.nombre.short
                max: 25
                maxMessage: acme_user.nombre.long
                groups: [ "Registration", "Profile" ]



# Note: We still want to validate the username
# See FOSUserBundle/Resources/config/validation/orm.xml to understand
# the UniqueEntity constraint that was originally applied to both
# username and username fields
#
# As you can see, we are only applying the UniqueEntity constraint to
# the username field and not the username field.
FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: username
             errorPath: username
             message: fos_user.username.already_used
             groups: [ "Registration", "Profile" ]

    properties:
        username:
            - NotBlank:
                message: fos_user.username.blank
                groups: [ "Registration", "Profile" ]
            - Length:
                min: 8
                minMessage: fos_user.username.short
                max: 8
                maxMessage: fos_user.username.long
                groups: [ "Registration", "ResetPassword" ]
            - Username:
                message: fos_user.username.invalid
                groups: [ "Registration", "Profile" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "Registration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 6
                max: 255
                minMessage: fos_user.password.short
                groups: [ "Registration", "Profile", "ResetPassword", "ChangePassword"]

FOS\UserBundle\Model\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "Registration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "Registration" ]

FOS\UserBundle\Propel\User:
    properties:
        username:
            - NotBlank:
                message: fos_user.username.blank
                groups: [ "Registration", "Profile" ]
            - Length:
                min: 8
                minMessage: fos_user.username.short
                max: 8
                maxMessage: fos_user.username.long
                groups: [ "Registration", "ResetPassword" ]
            - Username:
                message: fos_user.username.invalid
                groups: [ "Registration", "Profile" ]

        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "Registration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 6
                max: 255
                minMessage: fos_user.password.short
                groups: [ "Registration", "Profile", "ResetPassword", "ChangePassword"]


FOS\UserBundle\Propel\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "Registration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "Registration" ]
