<?php

namespace AppBundle\Repository;

/**
 * AgresorCorruptibilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgresorCorruptibilidadRepository extends \Doctrine\ORM\EntityRepository
{
}
