<?php

namespace AppBundle\Repository;

/**
 * AgresorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgresorRepository extends \Doctrine\ORM\EntityRepository{

  public function findAllSub($id){
    $query =$this->getEntityManager()
      ->createQuery('SELECT DISTINCT ac
        FROM AppBundle:Agresor a
        INNER JOIN AppBundle:AgresorCorruptibilidad ac
        INNER JOIN AppBundle:NivelCorruptibilidad nc
        WHERE a.id = :id AND a.id = ac.agresorId AND ac.corruptibilidadId = nc.id AND nc.padre > 0 AND nc.activo = 1')
      ->setParameter('id', $id)
      ->getResult();
    return $query;
  }


}
