<?php

namespace AppBundle\Repository;

/**
 * AgresorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgresorRepository extends \Doctrine\ORM\EntityRepository
{
}
