<?php

namespace AppBundle\Repository;

/**
 * AnexoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnexoRepository extends \Doctrine\ORM\EntityRepository
{
}
