<?php

namespace AppBundle\Repository;

/**
 * AntecedenteJudicialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntecedenteJudicialRepository extends \Doctrine\ORM\EntityRepository
{
}
