<?php

namespace AppBundle\Repository;

/**
 * BarrioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarrioRepository extends \Doctrine\ORM\EntityRepository
{
}
