<?php

namespace AppBundle\Repository;

/**
 * BotonAntipanicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotonAntipanicoRepository extends \Doctrine\ORM\EntityRepository
{
}
