<?php

namespace AppBundle\Repository;

/**
 * BotonAntipanicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotonAntipanicoRepository extends \Doctrine\ORM\EntityRepository{
  public function getBotonesEntreFechas($inicio,$fin){
    $query =$this->getEntityManager()
      ->createQuery('SELECT COUNT(b) FROM AppBundle:BotonAntipanico b WHERE b.fechaEntrega BETWEEN :inicio AND :fin')
      ->setParameter('inicio', $inicio)
      ->setParameter('fin', $fin)
      ->getSingleScalarResult();
    return $query;
  }
}
