<?php

namespace AppBundle\Repository;

/**
 * CoberturaSaludRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoberturaSaludRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllActive(){
		$query =$this->getEntityManager()
        ->createQuery('SELECT cs FROM AppBundle:CoberturaSalud cs WHERE cs.activo = 1')
        ->getResult();
      return $query;
	}
}
