<?php

namespace AppBundle\Repository;

/**
 * CoberturaSaludRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoberturaSaludRepository extends \Doctrine\ORM\EntityRepository
{
}
