<?php

namespace AppBundle\Repository;

/**
 * EstadoCivilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoCivilRepository extends \Doctrine\ORM\EntityRepository
{
}
