<?php

namespace AppBundle\Repository;

/**
 * EstadoDeSaludRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoDeSaludRepository extends \Doctrine\ORM\EntityRepository
{
}
