<?php

namespace AppBundle\Repository;

/**
 * EstadoDeSaludRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoDeSaludRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllActive(){
		$query =$this->getEntityManager()
        ->createQuery('SELECT es FROM AppBundle:EstadoDeSalud es WHERE es.activo = 1 ORDER BY es.orden')
        ->getResult();
      return $query;
	}
}
