<?php

namespace AppBundle\Repository;

/**
 * EvaluacionMedidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionMedidaRepository extends \Doctrine\ORM\EntityRepository
{
}
