<?php

namespace AppBundle\Repository;

/**
 * EvaluacionIntervencionJuzgadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionIntervencionJuzgadoRepository extends \Doctrine\ORM\EntityRepository
{
}
