<?php

namespace AppBundle\Repository;

/**
 * EvaluacionIndicadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionIndicadorRepository extends \Doctrine\ORM\EntityRepository
{
}
