<?php

namespace AppBundle\Repository;

/**
 * EvaluacionRiesgoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionRiesgoRepository extends \Doctrine\ORM\EntityRepository
{
}
