<?php

namespace AppBundle\Repository;

/**
 * ExpedienteCoberturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteCoberturaRepository extends \Doctrine\ORM\EntityRepository
{
}
