<?php

namespace AppBundle\Repository;

/**
 * ExpedienteSaludRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteSaludRepository extends \Doctrine\ORM\EntityRepository
{
}
