<?php

namespace AppBundle\Repository;

/**
 * ExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteRepository extends \Doctrine\ORM\EntityRepository{
  public function getExpedientesEntreFechas($inicio,$fin){
    $query =$this->getEntityManager()
      ->createQuery('SELECT COUNT(e) FROM AppBundle:Expediente e WHERE e.fecha BETWEEN :inicio AND :fin')
      ->setParameter('inicio', $inicio)
      ->setParameter('fin', $fin)
      ->getSingleScalarResult();
    return $query;
  }

}
