<?php

namespace AppBundle\Repository;

/**
 * ExpedienteRedesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteRedesRepository extends \Doctrine\ORM\EntityRepository
{
}
