<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class ExpedienteRepository extends \Doctrine\ORM\EntityRepository
{

  public function getAllExpedientes($currentPage = 1, $limit = 3){
      // Create our query
      $query = $this->createQueryBuilder('e')
          ->getQuery();
      $paginator = $this->paginate($query, $currentPage, $limit);
      return array('paginator' => $paginator, 'query' => $query);
  }


  public function paginate($dql, $page = 1, $limit = 3){
    $paginator = new Paginator($dql);

    $paginator->getQuery()
        ->setFirstResult($limit * ($page - 1)) // Offset
        ->setMaxResults($limit); // Limit

    return $paginator;

  }
  public function getExpedientesEntreFechas($inicio,$fin){
    $query =$this->getEntityManager()
      ->createQuery('SELECT COUNT(e) FROM AppBundle:Expediente e WHERE e.fecha BETWEEN :inicio AND :fin')
      ->setParameter('inicio', $inicio)
      ->setParameter('fin', $fin)
      ->getSingleScalarResult();
    return $query;
  }

}
