<?php

namespace AppBundle\Repository;

/**
 * HogarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HogarRepository extends \Doctrine\ORM\EntityRepository
{
}
