<?php

namespace AppBundle\Repository;

/**
 * IndicadorRiesgoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicadorRiesgoRepository extends \Doctrine\ORM\EntityRepository
{
}
