<?php

namespace AppBundle\Repository;

/**
 * IntervencionRealizadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervencionRealizadaRepository extends \Doctrine\ORM\EntityRepository
{
}
