<?php

namespace AppBundle\Repository;

/**
 * IntervencionFamiliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervencionFamiliaRepository extends \Doctrine\ORM\EntityRepository
{
}
