<?php

namespace AppBundle\Repository;

/**
 * IntervencionTipoIntervencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervencionTipoIntervencionRepository extends \Doctrine\ORM\EntityRepository
{
}
