<?php

namespace AppBundle\Repository;

/**
 * IntervencionJudicialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervencionJudicialRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllActive(){
		$query =$this->getEntityManager()
        ->createQuery('SELECT ij FROM AppBundle:IntervencionJudicial ij WHERE ij.activo = 1')
        ->getResult();
      return $query;
	}
}
