<?php

namespace AppBundle\Repository;

/**
 * IntervencionTipoPenalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervencionTipoPenalRepository extends \Doctrine\ORM\EntityRepository
{
}
