<?php

namespace AppBundle\Repository;

/**
 * IntervencionPenalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervencionPenalRepository extends \Doctrine\ORM\EntityRepository
{
}
