<?php

namespace AppBundle\Repository;

/**
 * IntervencionTipoFamiliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervencionTipoFamiliaRepository extends \Doctrine\ORM\EntityRepository
{
}
