<?php

namespace AppBundle\Repository;

/**
 * JuzgadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuzgadoRepository extends \Doctrine\ORM\EntityRepository
{
}
