<?php

namespace AppBundle\Repository;

/**
 * MedidaJudicialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedidaJudicialRepository extends \Doctrine\ORM\EntityRepository
{
}
