<?php

namespace AppBundle\Repository;

/**
 * NacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NacionRepository extends \Doctrine\ORM\EntityRepository
{
}
