<?php

namespace AppBundle\Repository;

/**
 * NivelCorruptibilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelCorruptibilidadRepository extends \Doctrine\ORM\EntityRepository
{
}
