<?php

namespace AppBundle\Repository;

/**
 * PerimetralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerimetralRepository extends \Doctrine\ORM\EntityRepository
{
}
