<?php

namespace AppBundle\Repository;

/**
 * RazonConsultaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RazonConsultaRepository extends \Doctrine\ORM\EntityRepository
{
}
