<?php

namespace AppBundle\Repository;

/**
 * RedesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedesRepository extends \Doctrine\ORM\EntityRepository
{
}
