<?php

namespace AppBundle\Repository;

/**
 * ResumenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResumenRepository extends \Doctrine\ORM\EntityRepository
{
}
