<?php

namespace AppBundle\Repository;

/**
 * SeguimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeguimientoRepository extends \Doctrine\ORM\EntityRepository{

  public function getSeguimientosEntreFechas($inicio,$fin){
    $query =$this->getEntityManager()
      ->createQuery('SELECT COUNT(s) FROM AppBundle:Seguimiento s WHERE s.fecha BETWEEN :inicio AND :fin')
      ->setParameter('inicio', $inicio)
      ->setParameter('fin', $fin)
      ->getSingleScalarResult();
    return $query;
  }
}
