<?php

namespace AppBundle\Repository;

/**
 * TipoAbogadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAbogadoRepository extends \Doctrine\ORM\EntityRepository
{
}
