<?php

namespace AppBundle\Repository;

/**
 * TipoIntervencionJudicialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoIntervencionJudicialRepository extends \Doctrine\ORM\EntityRepository
{
}
