<?php

namespace AppBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllActive(){
		$query =$this->getEntityManager()
        ->createQuery('SELECT u FROM AppBundle:Usuario u WHERE u.enabled = 1')
        ->getResult();
      return $query;
	}
}
