<?php

namespace AppBundle\Repository;

/**
 * VencimientoPerimetralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VencimientoPerimetralRepository extends \Doctrine\ORM\EntityRepository
{
}
