<?php

namespace AppBundle\Repository;

/**
 * VictimaEstadoSaludRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VictimaEstadoSaludRepository extends \Doctrine\ORM\EntityRepository
{
}
