<?php

namespace AppBundle\Repository;

/**
 * VictimaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VictimaRepository extends \Doctrine\ORM\EntityRepository
{
}
