<?php

namespace AppBundle\Repository;

/**
 * VictimaRedesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VictimaRedesRepository extends \Doctrine\ORM\EntityRepository
{
}
