<?php

namespace AppBundle\Repository;

/**
 * VictimaCoberturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VictimaCoberturaRepository extends \Doctrine\ORM\EntityRepository
{
}
