<?php

namespace AppBundle\Repository;

/**
 * VinculoSignificativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VinculoSignificativoRepository extends \Doctrine\ORM\EntityRepository
{
}
