<?php

namespace AppBundle\Repository;

/**
 * ViolenciaPadecidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViolenciaPadecidaRepository extends \Doctrine\ORM\EntityRepository
{
}
