<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3uy2et9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3uy2et9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3uy2et9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3uy2et9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3uy2et9\appDevDebugProjectContainer(array(
    'container.build_hash' => '3uy2et9',
    'container.build_id' => '03a62a06',
    'container.build_time' => 1540838682,
), __DIR__.\DIRECTORY_SEPARATOR.'Container3uy2et9');
