<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI1mm4lm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI1mm4lm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerI1mm4lm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerI1mm4lm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerI1mm4lm\appDevDebugProjectContainer(array(
    'container.build_hash' => 'I1mm4lm',
    'container.build_id' => '2dd8bd4a',
    'container.build_time' => 1540673711,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerI1mm4lm');
